# Generated by Django 3.2.8 on 2021-10-26 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('short_name', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('campaign', models.ForeignKey(help_text='Campaign', on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='responder.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('answer', models.ForeignKey(help_text='Answer', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='responder.answer')),
                ('campaign', models.ForeignKey(help_text='Campaign', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='responder.campaign')),
                ('language', models.ForeignKey(help_text='Language', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='responder.language')),
                ('topic', models.ForeignKey(help_text='Topic', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='responder.topic')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='campaign',
            field=models.ForeignKey(help_text='Campaign', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='responder.campaign'),
        ),
        migrations.AddField(
            model_name='answer',
            name='language',
            field=models.ForeignKey(help_text='Language', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='responder.language'),
        ),
    ]
