# Generated by Django 3.2.8 on 2021-10-20 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responder', 'search_vector_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('short_name', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('campaign', models.ForeignKey(help_text='Campaign', on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='responder.campaign')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='language',
            field=models.ForeignKey(default=1, help_text='Language', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='responder.language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='language',
            field=models.ForeignKey(default=1, help_text='Language', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='responder.language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(default=1, help_text='Topic', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='responder.topic'),
            preserve_default=False,
        ),
    ]
