# Generated by Django 3.2.8 on 2021-10-20 07:06

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0001_auto_20211020_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
