# Generated by Django 4.0.3 on 2022-03-31 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0003_alter_answer_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/% Y/% m/% d/')),
                ('campaign', models.ForeignKey(help_text='Campaign', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='responder.campaign')),
                ('topic', models.ForeignKey(help_text='Topic', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='responder.topic')),
            ],
        ),
    ]
