version: "3"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
      - postgres
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - C:\Users\user_pc\Desktop\kloop\data\journal-bb5e3-11e98ca4dace.json:/journal.json
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
  postgres:
    image: postgres:13
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
