version: "3"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
      - postgres
    command: python manage.py runserver 0.0.0.0:8000
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
